
svl clean info: [persistent] test_102_none.bcg

"test_102_none.bcg" = generation of "test_102_none.lnt"

svl clean info: [temporary] generator

svl clean info: [temporary] generator.o

svl clean info: [temporary] test_102_none.o

svl clean info: [temporary] test_102_none.err

% lnt.open   "test_102_none.lnt"  generator  "test_102_none.bcg"

lnt.open: translating ``common.lnt'' to ``/tmp/ls24_lnt.open_XYiS8h/COMMON.lib'' ...
/tmp/ls24_lnt.open_XYiS8h/common.lnt:293: warning: value stored in variable TID is not used later

lnt.open: translating ``test_102_none.lnt'' to ``/tmp/ls24_lnt.open_XYiS8h/test_102_none.lotos'' ...

lnt.open: calling lotos.open for ``test_102_none.lotos'' ...
lotos.open: using ``(direct) caesar''
lotos.open: calling ``caesar.adt -debug -silent test_102_none''
cadp_indent: cannot find ``indent''
             file ``test_102_none.h'' will not be formatted
lotos.open: calling ``lnt_check'' for ``test_102_none.h''
lotos.open: calling ``caesar -silent test_102_none''
#109 warning during restriction:
     detection of unreachable processes
In specification TEST_102_NONE [3]

   - process SCHEDULER_OBE [COMMON:335] is never reached

   - process LOOP__1 [COMMON:348] is never reached

   - process SCHEDULER_HSA [COMMON:374] is never reached

   - process LOOP__1 [COMMON:380] is never reached

   - process SCHEDULER_HSA_OBE [COMMON:397] is never reached

   - process LOOP__1 [COMMON:409] is never reached

   - process COND__2 [COMMON:434] is never reached

   - process LOOP__2 [COMMON:443] is never reached

   - process SCHEDULER_LOBE [COMMON:456] is never reached

   - process LOOP__1 [COMMON:465] is never reached

   - process COND__2 [COMMON:481] is never reached
#275 error in file ``.h'' :
     unexpected case (not defined by the equations)
     in operation MEMLOC [COMMON:31]
     implemented by function ADT_RANGE_CAST__MEMLOC__GENERATED [./test_102_none.h:2053]
         argument 1 = 2

#248 system error during simulation:
     termination on SOFTWARE_TERMINATION signal (files completed)
     quit
command exit with status 1

svl: ERROR command failed
